/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.fineract.infrastructure.jobs.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "job_processed_entity")
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class JobProcessedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // int8 GENERATED BY DEFAULT AS IDENTITY

    @Column(name = "job_id", nullable = false)
    private Long jobId; // int8 NOT NULL

    @Column(name = "execution_date", nullable = false)
    private LocalDate executionDate; // DATE NOT NULL

    @Column(name = "execution_process", nullable = false)
    private String executionProcess; // VARCHAR() NOT NULL

    @Column(name = "entity_type", nullable = false, length = 1)
    private String entityType; // CHAR(1) NOT NULL

    @Column(name = "entity_id", nullable = false)
    private Long entityId; // int8 NOT NULL

    @Column(name = "installment_nr", nullable = false)
    private Integer installmentNr; // int8 NOT NULL

    @Column(name = "start_time", nullable = false)
    private LocalDateTime startTime; // timestamp NOT NULL

    @Column(name = "end_time", nullable = false)
    private LocalDateTime endTime; // timestamp NOT NULL

    // O default '1' será definido no banco, mas aqui o JPA pode tratar como String
    @Column(name = "status", nullable = false, length = 1)
    private String status = "1"; // char(1) NOT NULL default '1'

    @Column(name = "error_message")
    private String errorMessage; // text NULL

    @Column(name = "error_log")
    private String errorLog; // text NULL
}
