echo "========== Login into AKS Cluster =========="
export AAD_SERVICE_PRINCIPAL_CLIENT_ID=$ARM_AKS_SERVICE_PRINCIPAL_ID
export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=$ARM_AKS_SERVICE_PRINCIPAL_KEY
export KUBECONFIG=$HOME/.kube/config
kubelogin convert-kubeconfig -l spn

echo "========== Define SERVICE_NAME variable key vaults =========="
SERVICE_NAME=${BUILD_REPOSITORY_NAME/incursor-back-/}

echo "========== Copy templates =========="
cp -r $SYSTEM_DEFAULTWORKINGDIRECTORY/$BUILD_REPOSITORY_NAME/.cicd/templates/ $SYSTEM_DEFAULTWORKINGDIRECTORY/incursor-back/helm/templates/

echo "========== Deleted secrets for key vaults =========="
kubectl delete secret kv-secrets-$SERVICE_NAME --namespace $ARM_AKS_NAMESPACE
kubectl delete secretproviderclass $SERVICE_NAME --namespace $ARM_AKS_NAMESPACE

echo "========== Upgrade Helm Chart =========="
HELM_CHART_PATH=$SYSTEM_DEFAULTWORKINGDIRECTORY/incursor-back/helm
HELM_PACKAGE_PATH=$SYSTEM_DEFAULTWORKINGDIRECTORY/microservices-nestjs-1.0.2.tgz
VALUES_HELM_PATH=$SYSTEM_DEFAULTWORKINGDIRECTORY/$BUILD_REPOSITORY_NAME/.cicd/values.yaml
helm package \
  --app-version="$IMAGE_VERSION" \
  --namespace="$FINERACT_AKS_NAMESPACE" \
  "$HELM_CHART_PATH" | \
    helm upgrade --namespace="$FINERACT_AKS_NAMESPACE" \
      --values $VALUES_HELM_PATH \
      --set namespace="$FINERACT_AKS_NAMESPACE" \
      --set replicaCount=$REPLICA_COUNT \
      \
      --set image.repository="$DOCKER_REGISTRY_DNS/$DOCKER_NAMESPACE/$SERVICE_NAME" \
      --set image.tag="$IMAGE_VERSION" \
      \
      --set keyVault.name="$ARM_KV_NAME" \
      --set keyVault.tenantId="$ARM_TENANT_ID" \
      --set keyVault.managedIdentityClientId="$ARM_KV_MANAGED_IDENTITY" \
      \
      --set ingress.hostname="$FINERACT_INGRESS_HOST" \
      --set ingress.redirectSSL="$FINERACT_INGRESS_REDIRECT_SSL" \
      --set ingress.privateIp="$FINERACT_INGRESS_PRIVATE_IP" \
      --set ingress.frontendPort="$FINERACT_INGRESS_FRONTEND_PORT" \
      \
      --set deployment.useSpotNode="$USE_SPOT_NODE" \
      \
      --set deployment.agentpool="$ARM_AKS_AGENT_POOL" \
      --set podDisruptionBudgets.enabled="$ENABLED_POD_DISRUPTION_BUDGETS" \
      \
      --set env.OTEL_SERVICE_NAME="$OTEL_SERVICE_NAME" \
      --set env.FINERACT_INSECURE_HTTP_CLIENT="$FINERACT_INSECURE_HTTP_CLIENT" \
      --set env.FINERACT_MANAGEMENT_METRICS_TAGS_APPLICATION="$FINERACT_MANAGEMENT_METRICS_TAGS_APPLICATION" \
      --set env.FINERACT_HIKARI_CONNECTION_TIMEOUT="$FINERACT_HIKARI_CONNECTION_TIMEOUT" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_USE_LOCAL_SESSION_STATE="$FINERACT_HIKARI_DS_PROPERTIES_USE_LOCAL_SESSION_STATE" \
      --set env.FINERACT_USER="$FINERACT_USER" \
      --set env.FINERACT_DEFAULT_TENANTDB_PORT="$FINERACT_DEFAULT_TENANTDB_PORT" \
      --set env.FINERACT_HIKARI_IDLE_TIMEOUT="$FINERACT_HIKARI_IDLE_TIMEOUT" \
      --set env.FINERACT_DEFAULT_TENANTDB_CONN_PARAMS="$FINERACT_DEFAULT_TENANTDB_CONN_PARAMS" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SQL_LIMIT="$FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SQL_LIMIT" \
      --set env.FINERACT_GROUP="$FINERACT_GROUP" \
      --set env.FINERACT_PENTAHO_REPORTS_PATH="$FINERACT_PENTAHO_REPORTS_PATH" \
      --set env.FINERACT_HIKARI_TEST_QUERY="$FINERACT_HIKARI_TEST_QUERY" \
      --set env.FINERACT_SERVER_SSL_ENABLED="$FINERACT_SERVER_SSL_ENABLED" \
      --set env.FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME="$FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME" \
      --set env.JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_CACHE_RESULT_SET_METADATA="$FINERACT_HIKARI_DS_PROPERTIES_CACHE_RESULT_SET_METADATA" \
      --set env.FINERACT_NODE_ID="$FINERACT_NODE_ID" \
      --set env.FINERACT_DEFAULT_TENANTDB_TIMEZONE="$FINERACT_DEFAULT_TENANTDB_TIMEZONE" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_REWRITE_BATCHED_STATEMENTS="$FINERACT_HIKARI_DS_PROPERTIES_REWRITE_BATCHED_STATEMENTS" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_CACHE_PREP_STMTS="$FINERACT_HIKARI_DS_PROPERTIES_CACHE_PREP_STMTS" \
      --set env.FINERACT_HIKARI_MAXIMUM_POOL_SIZE="$FINERACT_HIKARI_MAXIMUM_POOL_SIZE" \
      --set env.FINERACT_DEFAULT_MASTER_PASSWORD="$FINERACT_DEFAULT_MASTER_PASSWORD" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_LOG_SLOW_QUERIES="$FINERACT_HIKARI_DS_PROPERTIES_LOG_SLOW_QUERIES" \
      --set env.FINERACT_HIKARI_JDBC_URL="$FINERACT_HIKARI_JDBC_URL" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_CACHE_SERVER_CONFIGURATION="$FINERACT_HIKARI_DS_PROPERTIES_CACHE_SERVER_CONFIGURATION" \
      --set env.SPRING_PROFILES_ACTIVE="$SPRING_PROFILES_ACTIVE" \
      --set env.FINERACT_MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE="$FINERACT_MANAGEMENT_ENDPOINT_WEB_EXPOSURE_INCLUDE" \
      --set env.FINERACT_HIKARI_MINIMUM_IDLE="$FINERACT_HIKARI_MINIMUM_IDLE" \
      --set env.FINERACT_REMOTE_JOB_MESSAGE_HANDLER_SPRING_EVENTS_ENABLED="$FINERACT_REMOTE_JOB_MESSAGE_HANDLER_SPRING_EVENTS_ENABLED" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_ELIDE_SET_AUTO_COMMITS="$FINERACT_HIKARI_DS_PROPERTIES_ELIDE_SET_AUTO_COMMITS" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_MAINTAIN_TIME_STATS="$FINERACT_HIKARI_DS_PROPERTIES_MAINTAIN_TIME_STATS" \
      --set env.FINERACT_DEFAULT_TENANTDB_NAME="$FINERACT_DEFAULT_TENANTDB_NAME" \
      --set env.FINERACT_HIKARI_AUTO_COMMIT="$FINERACT_HIKARI_AUTO_COMMIT" \
      --set env.FINERACT_DEFAULT_TENANTDB_IDENTIFIER="$FINERACT_DEFAULT_TENANTDB_IDENTIFIER" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_USE_SERVER_PREP_STMTS="$FINERACT_HIKARI_DS_PROPERTIES_USE_SERVER_PREP_STMTS" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_DUMP_QUERIES_IN_EXCEPTION="$FINERACT_HIKARI_DS_PROPERTIES_DUMP_QUERIES_IN_EXCEPTION" \
      --set env.FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SIZE="$FINERACT_HIKARI_DS_PROPERTIES_PREP_STMT_CACHE_SIZE" \
      --set env.FINERACT_DEFAULT_TENANTDB_DESCRIPTION="$FINERACT_DEFAULT_TENANTDB_DESCRIPTION" \
      --set env.PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
      --set env.LANG="$LANG" \
      --set env.LANGUAGE="$LANGUAGE" \
      --set env.LC_ALL="$LC_ALL" \
      --set env.JAVA_HOME="$JAVA_HOME" \
      --set env.TZ="$TZ" \
      --set env.FINERACT_SERVER_PORT="$FINERACT_SERVER_PORT" \
      --set env.FINERACT_AZURE_AD_TENANT_ID="$FINERACT_AZURE_AD_TENANT_ID" \
      --set env.FINERACT_AZURE_AD_APP_CLIENT_ID="$FINERACT_AZURE_AD_APP_CLIENT_ID" \
      --set env.FINERACT_AZURE_AD_REDIRECT_URL="$FINERACT_AZURE_AD_REDIRECT_URL" \
      \
      --set deployment.resources.limits.cpu="$POD_LIMITS_CPU" \
      --set deployment.resources.limits.memory="$POD_LIMITS_MEMORY" \
      --set deployment.resources.requests.cpu="$POD_REQUESTS_CPU" \
      --set deployment.resources.requests.memory="$POD_REQUESTS_MEMORY" \
      \
      --wait \
      --debug \
      --install $SERVICE_NAME $HELM_PACKAGE_PATH