/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.fineract.portfolio.loanaccount.domain;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;

@Getter
@Entity
@Table(name = "PDA_Pagos")
public class LoanRepaymentImport {

    /*
     * Uploaded by ETL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id_pagos")
    private Long id;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Agencia_bancaria")
    private String bankingAgency;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Codigo_cliente")
    private Long customerCode;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Agencia")
    private String agency;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Codigo_prestamo", nullable = false)
    private String loanCode;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Codigo_producto")
    private String productCode;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Monto")
    private BigDecimal amount;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Boleta")
    private String receiptNumber;

    /*
     * Uploaded by ETL & update by Mifos
     */
    @Column(name = "Estado")
    private Long status;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Fecha_carga")
    private LocalDateTime uploadDate;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Hora_carga")
    private LocalTime uploadTime;

    /*
     * Generated by Mifos
     */
    @Column(name = "Feha_procesamiento_mifos")
    private LocalDateTime mifosProcessingDate;

    /*
     * Generated by Mifos
     */
    @Column(name = "Hora_procesamiento_mifos")
    private LocalTime mifosProcessingTime;

    /*
     * Generated by Mifos
     */
    @Column(name = "Nombre_archivo")
    private String mifosFileName;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Banco")
    private String bankName;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Grupo")
    private Long groupNumber;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Codigo_producto_mifos")
    private Long mifosProductCode;

    /*
     * Uploaded by ETL
     */
    @Column(name = "Fecha_pago")
    private LocalDate paymentDate;

    /*
     * Generated by Mifos
     */
    @Column(name = "Resultado_operacion")
    private String operationResult;

    /*
     * Generated by Mifos
     */
    @Column(name = "Monto_pago_programado")
    private BigDecimal scheduledPaymentAmount;

    /*
     * Generated by Mifos
     */
    @Column(name = "Numero_de_pago")
    private Long paymentNumber;

    /*
     * Generated by Mifos
     */
    @Column(name = "Ultimo_pago")
    private String lastPayment;

    /*
     * Generated by Mifos
     */
    @Column(name = "Tolerancia")
    private String tolerance;

    /*
     * Generated by Mifos
     */
    @Column(name = "Id_error")
    private Long errorId;

    public void resetMifosFields() {
        this.status = null;
        this.mifosProcessingDate = null;
        this.mifosProcessingTime = null;
        this.mifosFileName = null;
        this.operationResult = null;
        this.scheduledPaymentAmount = null;
        this.paymentNumber = null;
        this.lastPayment = null;
        this.tolerance = null;
        this.errorId = null;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public void setMifosProcessingDate(LocalDateTime mifosProcessingDate) {
        this.mifosProcessingDate = mifosProcessingDate;
    }

    public void setMifosProcessingTime(LocalTime mifosProcessingTime) {
        this.mifosProcessingTime = mifosProcessingTime;
    }

    public void setMifosFileName(String mifosFileName) {
        this.mifosFileName = mifosFileName;
    }

    public void setOperationResult(String operationResult) {
        this.operationResult = operationResult;
    }

    public void setScheduledPaymentAmount(BigDecimal schedulePaymentAmount) {
        this.scheduledPaymentAmount = schedulePaymentAmount;
    }

    public void setPaymentNumber(Long paymentNumber) {
        this.paymentNumber = paymentNumber;
    }

    public void setLastPayment(String lastPayment) {
        this.lastPayment = lastPayment;
    }

    public void setTolerance(String tolerance) {
        this.tolerance = tolerance;
    }

    public void setErrorId(Long errorId) {
        this.errorId = errorId;
    }
}
