--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- liquibase formatted sql
-- changeset fineract:2
-- MySQL dump 10.13  Distrib 5.1.60, for Win32 (ia32)
--
-- Host: localhost    Database: fineract_default
-- ------------------------------------------------------
-- Server version	5.1.60-community

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES UTF8MB4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Insert code values into m_code_value for code Lmunicipio
--

INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Acatenango', '411', 0, 140101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Agua Blanca', '2204', 0, 130101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Aguacatán', '1327', 0, 160101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Almolonga', '913', 0, 150201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Alotenango', '314', 0, 140201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Amatitlán', '114', 0, 100101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Antigua Guatemala', '301', 0, 140202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Asunción Mita', '2205', 0, 130102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Atescatempa', '2207', 0, 130103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ayutla', '1217', 0, 150101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Barberena', '602', 0, 130301, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Barillas', '1326', 0, 160102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cabañas', '1907', 0, 120301, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cabricán', '906', 0, 150202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cahabón', '1612', 0, 110101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cajolá', '907', 0, 150203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Camotán', '2005', 0, 120201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Canillá', '1418', 0, 160201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cantel', '914', 0, 150204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Casillas', '604', 0, 130302, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Catarina', '1216', 0, 150102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chahal', '1614', 0, 110102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chajul', '1405', 0, 160202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Champerico', '1107', 0, 150502, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chiantla', '1302', 0, 160103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chicacao', '1013', 0, 150601, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chicamán', '1419', 0, 160203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chiché', '1402', 0, 160204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chichicastenango', '1406', 0, 160205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chimaltenango', '401', 0, 140102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chinautla', '106', 0, 100102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chinique', '1403', 0, 160206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chiquimula', '2001', 0, 120202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chiquimulilla', '608', 0, 130303, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chisec', '1613', 0, 110103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Chuarrancho', '112', 0, 100103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ciudad Vieja', '312', 0, 140203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Coatepeque', '920', 0, 150205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cobán', '1601', 0, 110104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Colomba', '917', 0, 150206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Colotenango', '1319', 0, 160104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Comalapa', '404', 0, 140109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Comapa', '2211', 0, 130104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Comitancillo', '1204', 0, 150103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Concepción', '708', 0, 160105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Concepción Chiquirichapa', '911', 0, 150207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Concepción Huista', '1322', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Concepción Las Minas', '2008', 0, 120203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Concepción Tutuapa', '1206', 0, 150104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Conguaco', '2213', 0, 130105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cubulco', '1504', 0, 110201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cuilapa', '601', 0, 130304, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cuilco', '1304', 0, 160106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cunén', '1410', 0, 160207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Cuyotenango', '1002', 0, 150602, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Dolores', '1708', 0, 170101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Adelanto', '2209', 0, 130106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Asintal', '1109', 0, 150501, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Chal', '1714', 0, 170115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Chol', '1506', 0, 110202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Estor', '1803', 0, 120101, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Jícaro', '205', 0, 120401, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Palmar', '919', 0, 150208, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Progreso', '2202', 0, 130107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Quetzal', '1220', 0, 150105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Rodeo', '1214', 0, 150106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Tejar', '416', 0, 140103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'El Tumbador', '1213', 0, 150107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Escuintla', '501', 0, 140301, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Esquipulas', '2007', 0, 120204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Esquipulas Palo Gordo', '1227', 0, 150108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Estanzuela', '1902', 0, 120302, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Flores', '1701', 0, 170102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Flores Costa Cuca', '922', 0, 150209, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Fraijanes', '113', 0, 100104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Fray Bartolomé de las Casas', '1615', 0, 110105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Génova', '921', 0, 150210, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Granados', '1505', 0, 110203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Gualán', '1904', 0, 120303, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Guanagazapa', '508', 0, 140302, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Guastatoya', '201', 0, 120402, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Guatemala', '101', 0, 100105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Guazacapán', '611', 0, 130305, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Huehuetenango', '1301', 0, 160107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Huitán', '915', 0, 150211, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Huité', '1910', 0, 120304, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ipala', '2011', 0, 120205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ixcán', '1420', 0, 160208, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ixchiguán', '1223', 0, 150109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ixtahuacán', '1309', 0, 160108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Iztapa', '510', 0, 140303, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jacaltenango', '1307', 0, 160109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jalapa', '2101', 0, 130201, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jalpatagua', '2212', 0, 130108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jerez', '2208', 0, 130109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jocotán', '2004', 0, 120206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jocotenango', '302', 0, 140204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Joyabaj', '1412', 0, 160209, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Jutiapa', '2201', 0, 130110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Blanca', '1230', 0, 150131, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Democracia - Huehuetenango', '1312', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Democracia - Escuintla', '503', 0, 160110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Esperanza', '923', 0, 150212, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Gomera', '507', 0, 140305, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Libertad - Petén', '1705', 0, 170103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Libertad - Huehuetenango', '1311', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Reforma', '1221', 0, 150110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'La Unión', '1909', 0, 120305, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Lanquín', '1611', 0, 110106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Las Cruces', '1713', 0, 170114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Livingston', '1802', 0, 120102, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Los Amates', '1805', 0, 120103, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Magdalena Milpas Altas', '310', 0, 140205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Malacatán', '1215', 0, 150111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Malacatancito', '1303', 0, 160112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Masagua', '505', 0, 140306, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Mataquescuintla', '2107', 0, 130202, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Mazatenango', '1001', 0, 150603, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Melchor de Mencos', '1711', 0, 170104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Mixco', '108', 0, 100106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Momostenango', '805', 0, 150301, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Monjas', '2106', 0, 130203, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Morales', '1804', 0, 120104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Morazán', '202', 0, 120403, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Moyuta', '2214', 0, 130111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nahualá', '705', 0, 150402, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nebaj', '1413', 0, 160210, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nentón', '1305', 0, 160113, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nueva Concepción', '513', 0, 140307, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nueva Santa Rosa', '614', 0, 130306, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nuevo Progreso', '1212', 0, 150112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Nuevo San Carlos', '1108', 0, 150503, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ocós', '1218', 0, 150113, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Olintepeque', '903', 0, 150213, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Olopa', '2006', 0, 120207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Oratorio', '606', 0, 130307, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Ostuncalco', '909', 0, 150219, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pachalum', '1421', 0, 160211, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pajapita', '1222', 0, 150114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Palencia', '105', 0, 100107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Palestina de los Altos', '924', 0, 150214, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Palín', '511', 0, 140308, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Panajachel', '710', 0, 150403, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Panzós', '1607', 0, 110107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Parramos', '414', 0, 140104, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pasaco', '2215', 0, 130112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pastores', '303', 0, 140206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Patulul', '1014', 0, 150604, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Patzicía', '409', 0, 140105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Patzité', '1407', 0, 160212, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Patzún', '407', 0, 140106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Petapa', '117', 0, 100111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pochuta', '408', 0, 140111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Poptún', '1712', 0, 170105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pueblo Nuevo', '1019', 0, 150605, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Pueblo Nuevo Viñas', '613', 0, 130308, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Puerto Barrios', '1801', 0, 120105, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Purulhá', '1508', 0, 110204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Quesada', '2217', 0, 130113, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Quetzaltenango', '901', 0, 150215, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Quetzaltepeque', '2009', 0, 120208, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Rabinal', '1503', 0, 110205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Raxruhá', '1617', 0, 110117, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Retalhuleu', '1101', 0, 150504, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Río Blanco', '1228', 0, 150115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Río Bravo', '1020', 0, 150606, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Río Hondo', '1903', 0, 120306, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sacapulas', '1416', 0, 160213, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Salamá', '1501', 0, 110206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Salcajá', '902', 0, 150216, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Samayac', '1008', 0, 150607, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Agustín Acasaguastlán', '203', 0, 120404, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés', '1704', 0, 170106, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés Itzapa', '413', 0, 140107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés Sajcabajá', '1414', 0, 160214, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés Semetabaj', '709', 0, 150404, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés Villa Seca', '1106', 0, 150505, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Andrés Xecul', '804', 0, 150302, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Aguas Calientes', '315', 0, 140207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Huista', '1324', 0, 160114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Ilotenango', '1408', 0, 160215, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio la Paz', '208', 0, 120405, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Palopó', '712', 0, 150405, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Sacatepéquez', '1203', 0, 150116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Antonio Suchitepéquez', '1010', 0, 150608, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Bartolo', '808', 0, 150303, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Bartolomé Jocotenango', '1417', 0, 160216, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Bartolomé Milpas Altas', '307', 0, 140208, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Benito', '1703', 0, 170107, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Bernardino', '1004', 0, 150609, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Carlos Alzatate', '2105', 0, 130204, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Carlos Sija', '904', 0, 150217, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Cristóbal Acasaguastlán', '204', 0, 120406, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Cristóbal Cucho', '1225', 0, 150117, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Cristóbal Totonicapán', '802', 0, 150304, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Cristóbal Verapaz', '1603', 0, 110108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Diego', '1908', 0, 120307, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Felipe', '1105', 0, 150507, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Francisco', '1706', 0, 170108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Francisco el Alto', '803', 0, 150305, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Francisco la Unión', '918', 0, 150218, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Francisco Zapotitlán', '1003', 0, 150610, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Gabriel', '1012', 0, 150611, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Gaspar Ixchil', '1329', 0, 160115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Jacinto', '2010', 0, 120209, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Jerónimo', '1507', 0, 110207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Jorge', '1911', 0, 120311, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José', '1702', 0, 140309, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José - Escuintla', '509', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José Acatempa', '2216', 0, 130114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José Chacayá', '702', 0, 150406, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José del Golfo', '104', 0, 100108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José el Idolo', '1005', 0, 150612, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José La Arada', '2002', 0, 120210, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José La Máquina', '1021', 0, 150621, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José Ojetenán', '1224', 0, 150118, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José Pinula', '103', 0, 100109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San José Poaquil', '402', 0, 140108, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Atitán', '1316', 0, 160116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Bautista', '1016', 0, 150613, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Chamelco', '1610', 0, 110109, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Cotzal', '1411', 0, 160217, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Ermita', '2003', 0, 120211, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Ixcoy', '1323', 0, 160117, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan la Laguna', '717', 0, 150407, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Sacatepéquez', '110', 0, 100110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Juan Tecuaco', '607', 0, 130309, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Lorenzo', '1007', 0, 150614, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Lorenzo San Marcos', '1229', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Lucas Sacatepéquez', '308', 0, 140209, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Lucas Tolimán', '713', 0, 150408, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Luis', '1709', 0, 170110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Luis Jilotepeque', '2103', 0, 130205, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Manuel Chaparrón', '2104', 0, 130206, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Marcos', '1201', 0, 150120, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Marcos la Laguna', '716', 0, 150409, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Martín Jilotepeque', '403', 0, 140110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Martín Sacatepéquez', '912', 0, 150220, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Martín Zapotitlán', '1104', 0, 150508, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Mateo', '910', 0, 150221, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Mateo Ixtatán', '1318', 0, 160118, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Acatán', '1313', 0, 160119, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Chicaj', '1502', 0, 110208, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Dueñas', '313', 0, 140210, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Ixtahuacán', '1205', 0, 150121, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Panán', '1011', 0, 150615, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Miguel Siguilá', '908', 0, 150222, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pablo', '1219', 0, 150122, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pablo Jocopilas', '1009', 0, 150616, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pablo la Laguna', '715', 0, 150410, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Ayampuc', '107', 0, 100112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Carchá', '1609', 0, 110110, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Jocopilas', '1409', 0, 160219, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro la Laguna', '718', 0, 150411, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Necta', '1306', 0, 160120, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Pinula', '2102', 0, 130207, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Sacatepéquez - Guatemala', '109', 0, 150123, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Pedro Sacatepéquez - San Marcos', '502', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Rafael la Independencia', '1314', 0, 160121, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Rafael las Flores', '605', 0, 130310, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Rafael Petzal', '1328', 0, 160122, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Rafael Pié de la Cuesta', '1211', 0, 150124, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Raymundo', '111', 0, 100114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Sebastián', '1102', 0, 150509, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Sebastián Coatán', '1325', 0, 160123, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Sebastián Huehuetenango', '1320', 0, 160124, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'San Vicente Pacaya', '512', 0, 140310, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sanarate', '207', 0, 120407, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sansare', '206', 0, 120408, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Ana', '1707', 0, 170111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Ana Huista', '1331', 0, 160125, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Apolonia', '405', 0, 140113, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Bárbara - Huehuetenango', '1310', 0, 0, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Bárbara', '1015', 0, 160126, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catalina la Tinta', '1616', 0, 110116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catarina Barahona', '316', 0, 140211, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catarina Ixtahuacán', '706', 0, 150412, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catarina Mita', '2203', 0, 130115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catarina Palopó', '711', 0, 150413, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Catarina Pinula', '102', 0, 100115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Clara la Laguna', '707', 0, 150414, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz Balanyá', '410', 0, 140114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz del Quiché', '1401', 0, 160220, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz la Laguna', '714', 0, 150415, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz Muluá', '1103', 0, 150506, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz Naranjo', '612', 0, 130311, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Cruz Verapaz', '1602', 0, 110111, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Eulalia', '1317', 0, 160127, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Lucía Cotzumalguapa', '502', 0, 140311, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Lucía la Reforma', '807', 0, 150306, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Lucía Milpas Altas', '309', 0, 140212, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Lucía Utatlán', '704', 0, 150416, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa María Chiquimula', '806', 0, 150307, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa María de Jesús', '311', 0, 140213, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa María Ixhuatán', '610', 0, 130312, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa María Visitación', '703', 0, 150417, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santa Rosa de Lima', '603', 0, 130313, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santiago Atitlán', '719', 0, 150418, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santiago Chimaltenango', '1330', 0, 160128, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santiago Sacatepéquez', '306', 0, 140214, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santo Domingo Suchitepéquez', '1006', 0, 150618, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santo Domingo Xenacoj', '305', 0, 140215, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Santo Tomás la Unión', '1017', 0, 150619, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sayaxché', '1710', 0, 170112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Senahú', '1608', 0, 110112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sibilia', '905', 0, 150223, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sibinal', '1208', 0, 150125, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sipacapa', '1226', 0, 150126, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Siquinalá', '504', 0, 140312, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sololá', '701', 0, 150419, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Soloma', '1308', 0, 160129, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Sumpango', '304', 0, 140216, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tacaná', '1207', 0, 150127, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tactic', '1604', 0, 110113, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tajumulco', '1209', 0, 150128, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tamahú', '1605', 0, 110114, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Taxisco', '609', 0, 130314, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tecpán Guatemala', '406', 0, 140115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tectitán', '1321', 0, 160130, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Teculután', '1905', 0, 120308, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tejutla', '1210', 0, 150129, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tiquisate', '506', 0, 140313, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Todos Santos Cuchumatán', '1315', 0, 160131, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Totonicapán', '801', 0, 150308, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Tucurú', '1606', 0, 110115, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Unión Cantinil', '1332', 0, 160132, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Uspantán', '1415', 0, 160218, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Usumatlán', '1906', 0, 120309, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Villa Canales', '116', 0, 100116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Villa Nueva', '115', 0, 100117, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Yepocapa', '412', 0, 140112, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Yupiltepeque', '2206', 0, 130116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zacapa', '1901', 0, 120310, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zacualpa', '1404', 0, 160221, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zapotitlán', '2210', 0, 130117, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zaragoza', '415', 0, 140116, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zunil', '916', 0, 150224, 1, 0);
INSERT INTO `fineract_default`.`m_code_value`(`code_id`, `code_value`, `code_description`, `order_position`, `code_score`, `is_active`, `is_mandatory`) VALUES (40, 'Zunilito', '1018', 0, 150620, 1, 0);
