--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- liquibase formatted sql
-- changeset fineract:1
-- MySQL dump 10.13  Distrib 5.1.60, for Win32 (ia32)
--
-- Host: localhost    Database: fineract_default
-- ------------------------------------------------------
-- Server version	5.1.60-community

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES UTF8MB4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `checklist_categories` (
                                        `id` bigint NOT NULL AUTO_INCREMENT,
                                        `name` varchar(255) DEFAULT NULL,
                                        `description` varchar(255) DEFAULT NULL,
                                        PRIMARY KEY (`id`)
);

INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (1, 'New Client', 'label.category.newclient');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (2, 'Recurring Customer', 'label.category.recurringcustomer');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (3, 'Increase Percentage', 'label.category.increasepercentage');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (4, 'Mandatory Photographs', 'label.category.mandatoryphotos');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (5, 'Client Age', 'label.category.clientage');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (6, 'No. Of Members according To Policy', 'label.category.memberspolicycount');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (7, 'Minimum and Maximum Amount', 'label.category.minmaxamount');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (8, 'Disparity of Values', 'label.category.disparity');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (9, 'Percent Of Members Starting Business', 'label.category.startingbusiness');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (10, 'Percent Of Members with their own home', 'label.category.ownhome');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (11, 'Chairman of The BC Board Of Directors', 'label.category.boardofdirectors');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (12, 'Overall Condition', 'label.category.overallcondition');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (13, 'Categories of clients to accept', 'label.category.clientcategories');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (14, 'Requested Amount', 'label.category.requestedamount');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (15, 'add_endorsemnet', 'label.category.addendorsement');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (16, 'Payments Outside Current Term', 'label.category.outsidetermpayents');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (17, 'Percentage Of members that can have Product', 'label.category.canhaveproduct');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (18, 'Gender', 'label.category.gender');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (19, 'Nationality', 'label.category.nationality');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (20, 'Internal Credit History', 'label.category.internalcredithistory');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (21, 'External Credit History', 'label.category.externalcredithistory');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (22, 'Claim Registered', 'label.category.claimregistered');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (23, 'Housing Type', 'label.category.housingtype');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (24, 'Rental Age', 'label.category.rentalage');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (25, 'Age Of Business', 'label.category.businessage');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (26, 'Credits', 'label.category.credits');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (27, 'Cancelled Cycles Count', 'label.category.cyclescount');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (28, ' Submit agricultural technical diagnosis (Commcare)', 'label.category.mandatoryphotos');
INSERT INTO `fineract_default`.`checklist_categories` (`id`, `name`, `description`) VALUES (29, ' Acceptance of new clients', 'label.category.newclientsacceptance');

CREATE TABLE `checklist_decision_making` (
                                             `id` bigint NOT NULL AUTO_INCREMENT,
                                             `checklist_category_id` int NOT NULL,
                                             `sequence` int DEFAULT NULL,
                                             `reference` varchar(255) DEFAULT NULL,
                                             `condition` varchar(255) DEFAULT NULL,
                                             `first_value` varchar(255) DEFAULT NULL,
                                             `second_value` varchar(255) DEFAULT NULL,
                                             `value_list` varchar(255) DEFAULT NULL,
                                             `color` varchar(255) DEFAULT NULL,
                                             `description` varchar(255) DEFAULT NULL,
                                             `product_id` bigint DEFAULT NULL,
                                             PRIMARY KEY (`id`),
                                             KEY `product_id` (`product_id`) USING BTREE,
                                             CONSTRAINT `checklist_decision_making_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `m_product_loan` (`id`) ON UPDATE RESTRICT
);

INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (1, 1, 1, 'Cycles', 'EQUAL', '0', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (2, 1, 2, ' Returns to the institution after (years)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (3, 1, 3, ' canceled cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (4, 2, 1, 'Cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (5, 3, 1, 'Amount increase Percentage', 'EQUAL', '200', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (6, 3, 2, 'Amount increase Percentage', 'BETWEEN', '201', '500', NULL, 'YELLOW', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (7, 3, 3, 'Amount increase Percentage', 'GREATER', '500', NULL, NULL, 'RED', 'EXCEPTION', 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (8, 4, 1, 'Cycles', 'EQUAL', '0', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (9, 4, 2, 'Returns After Years', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (10, 4, 3, 'Canceled Cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (11, 4, 4, 'Requested Amount', 'GREATER', '6000', NULL, NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (12, 5, 1, 'New Client Age', 'BETWEEN', '18', '70', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (13, 5, 2, 'New Client Age', 'BETWEEN', '71', '75', NULL, 'YELLOW', 'EXCEPTION', 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (14, 5, 3, 'New Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (15, 5, 4, 'Recurring Client Age', 'BETWEEN', '18', '75', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (16, 5, 5, 'Recurring Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (17, 6, 1, ' New (URBAN)', ' GREATER_OR_EQUAL', '7', '', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (18, 6, 2, ' Recredit (URBAN)', '  GREATER_OR_EQUAL', '7', '', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (19, 6, 3, ' New (RURAL)', '  GREATER_OR_EQUAL', '10', '', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (20, 6, 4, ' Recredit (RURAL)', '  GREATER_OR_EQUAL', '10', '', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (21, 7, 1, ' New (URBAN)', ' BETWEEN', '1500', '5000', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (22, 7, 2, ' Recredit (URBAN)', 'BETWEEN', '1500', '15000', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (23, 7, 3, ' New (RURAL)', 'BETWEEN', '1500', '5000', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (24, 7, 4, ' Recredit (RURAL)', 'BETWEEN', '1500', '15000', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (25, 8, 1, ' New (URBAN)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (26, 8, 2, ' New (URBAN)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (27, 8, 3, ' Recredit (URBAN)', 'BETWEEN', '1', '4', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (28, 8, 4, ' Recredit (URBAN)', 'GREATER', '4', NULL, NULL, 'YELLOW', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (29, 8, 5, ' New (RURAL)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (30, 8, 6, ' New (RURAL)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (31, 8, 7, ' Recredit (RURAL)', 'BETWEEN', '1', '4', NULL, 'GREEN', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (32, 8, 8, ' Recredit (RURAL)', 'GREATER', '4', NULL, NULL, 'YELLOW', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (33, 9, 1, NULL, 'LESS_OR_EQUAL', '20', NULL, NULL, ' Green', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (34, 9, 2, NULL, 'GREATER', '20', NULL, NULL, ' Yellow', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (35, 10, 1, NULL, 'LESS_OR_EQUAL', '50', NULL, NULL, ' Green', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (36, 10, 2, NULL, 'GREATER', '50', NULL, NULL, ' Yellow', NULL, 2);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (37, 1, 1, ' cycles', 'EQUAL', '0', NULL, NULL, ' Green', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (38, 1, 2, ' Returns to the institution after (years)', 'GREATER_OR_EQUAL', '1', NULL, NULL, ' Green', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (39, 1, 3, ' canceled cycles', 'GREATER', '0', NULL, NULL, ' Green', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (40, 2, 1, 'Cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (41, 3, 1, 'Amount increase Percentage', 'EQUAL', '200', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (42, 3, 2, 'Amount increase Percentage', 'BETWEEN', '201', '500', NULL, 'YELLOW', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (43, 3, 3, 'Amount increase Percentage', 'GREATER', '500', NULL, NULL, 'RED', 'EXCEPTION', 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (44, 4, 1, 'Cycles', 'EQUAL', '0', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (45, 4, 2, 'Returns After Years', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (46, 4, 3, 'Canceled Cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (47, 4, 4, 'Requested Amount', 'GREATER', '6000', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (48, 5, 1, 'New Client Age', 'BETWEEN', '18', '70', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (49, 5, 2, 'New Client Age', 'BETWEEN', '71', '75', NULL, 'YELLOW', 'EXCEPTION', 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (50, 5, 3, 'New Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (51, 5, 4, 'Recurring Client Age', 'BETWEEN', '18', '75', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (52, 5, 5, 'Recurring Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (53, 27, 1, ' Recredit (URBAN)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (54, 27, 2, ' Recredit (RURAL)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (55, 6, 1, ' Recredit (URBAN)', ' GREATER_OR_EQUAL', '4', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (56, 6, 2, ' Recredit (URBAN)', 'LESS', '4', NULL, NULL, 'ORANGE', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (57, 6, 3, ' Recredit (RURAL)', 'GREATER_OR_EQUAL', '4', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (58, 6, 4, ' Recredit (RURAL)', 'LESS', '4', NULL, NULL, 'ORANGE', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (59, 7, 1, ' Recredit (URBAN)', 'BETWEEN', '1500', '15000', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (60, 7, 2, ' Recredit (RURAL)', 'BETWEEN', '1500', '15000', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (61, 8, 1, ' Recredit (URBAN)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (62, 8, 2, ' Recredit (URBAN)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (63, 8, 3, ' Recredit (RURAL)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (64, 8, 4, ' Recredit (RURAL)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (65, 11, 1, '', 'EQUAL', ' TO', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (66, 11, 2, '', 'EQUAL', ' B.', NULL, NULL, 'GREEN', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (67, 11, 3, '', 'EQUAL', ' C.', NULL, NULL, 'YELLOW', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (68, 11, 4, '', 'EQUAL', ' D.', NULL, NULL, 'ORANGE', NULL, 9);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (69, 1, 1, ' cycles', ' EQUAL', '0', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (70, 1, 2, ' Returns to the institution after (years)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (71, 1, 3, ' canceled cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (72, 2, 1, 'Cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (73, 3, 1, 'Amount increase Percentage', 'EQUAL', '200', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (74, 3, 2, 'Amount increase Percentage', 'BETWEEN', '201', '500', NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (75, 3, 3, 'Amount increase Percentage', 'GREATER', '500', NULL, NULL, 'RED', 'EXCEPTION', 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (76, 4, 1, 'Clients', 'EQUAL', 'ALL', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (77, 28, 1, 'Clients', 'EQUAL', 'ALL', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (78, 5, 1, 'New Client Age', 'BETWEEN', '18', '70', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (79, 5, 2, 'New Client Age', 'BETWEEN', '71', '75', NULL, 'YELLOW', 'EXCEPTION', 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (80, 5, 3, 'New Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (81, 5, 4, 'Recurring Client Age', 'BETWEEN', '18', '75', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (82, 5, 5, 'Recurring Client Age', 'LESS_AND_GREATER', '18', '75', NULL, 'RED', 'REJECT', 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (83, 6, 1, ' New (URBAN)', 'GREATER_OR_EQUAL', '7', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (84, 6, 2, ' New (URBAN)', 'LESS', '7', NULL, NULL, 'ORANGE', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (85, 6, 3, ' Recredit (URBAN)', 'GREATER_OR_EQUAL', '7', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (86, 6, 4, ' Recredit (URBAN)', 'LESS', '7', NULL, NULL, 'ORANGE', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (87, 6, 5, ' New (RURAL)', 'GREATER_OR_EQUAL', '10', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (88, 6, 6, ' New (RURAL)', 'LESS', '10', NULL, NULL, 'ORANGE', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (89, 6, 7, ' Recredit (RURAL)', 'GREATER_OR_EQUAL', '10', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (90, 6, 8, ' Recredit (RURAL)', 'LESS', '10', NULL, NULL, 'ORANGE', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (91, 7, 1, ' New (URBAN)', ' BETWEEN', '1000', '4999', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (92, 7, 2, ' Recredit (URBAN)', 'BETWEEN', '1000', '20000', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (93, 7, 3, ' New (RURAL)', 'BETWEEN', '1000', '4999', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (94, 7, 4, ' Recredit (RURAL)', 'BETWEEN', '1000', '20000', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (95, 8, 1, ' New (URBAN)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (96, 8, 2, ' New (URBAN)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (97, 8, 3, ' Recredit (URBAN)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (98, 8, 4, ' Recredit (URBAN)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (99, 8, 5, ' New (RURAL)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (100, 8, 6, ' New (RURAL)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (101, 8, 7, ' Recredit (RURAL)', 'BETWEEN', '1', '3', NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (102, 8, 8, ' Recredit (RURAL)', 'GREATER', '3', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (103, 10, 1, NULL, ' GREATER_OR_EQUAL', '50', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (104, 10, 2, NULL, 'GREATER', '50', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (105, 11, 1, NULL, 'EQUAL', ' TO', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (106, 11, 2, NULL, 'EQUAL', ' B.', NULL, NULL, 'GREEN', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (107, 11, 3, NULL, 'EQUAL', ' C.', NULL, NULL, 'YELLOW', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (108, 11, 4, NULL, 'EQUAL', ' D.', NULL, NULL, 'ORANGE', NULL, 8);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (109, 1, 1, ' cycles', ' EQUAL', '0', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (110, 1, 2, ' Returns to the institution after (years)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (111, 1, 3, ' canceled cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (112, 2, 1, ' Complete and canceled cycles main BC products', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (113, 3, 1, ' Amount increase percentages', ' LESS_OR_EQUAL', '60', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (114, 3, 2, ' Amount increase percentages', 'LESS', '60', NULL, NULL, 'ORANGE', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (115, 4, 1, 'Clients', 'EQUAL', 'ALL', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (116, 5, 1, ' new client age', ' BETWEEN', '18', '70', NULL, ' GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (117, 5, 2, ' New client age (Exception)', 'BETWEEN', '71', '75', NULL, 'YELLOW', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (118, 5, 3, ' New customer age (Rejected)', 'NOT_BETWEEN', '18', '75', NULL, 'RED', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (119, 5, 4, ' Recurring customer age', 'BETWEEN', '18', '75', NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (120, 5, 5, ' Recurring customer age (Rejected)', 'NOT_BETWEEN', '18', '75', NULL, 'RED', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (121, 6, 1, ' Recredit (URBAN)', ' GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (122, 6, 2, ' Recredit (RURAL)', ' GREATER_OR_EQUAL', '4', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (123, 29, 1, ' Recrédito (URBANO), 1 new client for how many recurring clients', 'EQUAL', '3', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (124, 29, 2, ' Recredito (RURAL), 1 new client for how many recurring clients', 'EQUAL', '3', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (125, 7, 1, ' Recredit (URBAN)', 'BETWEEN', '6000', '20000', NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (126, 7, 2, ' Recredit (RURAL)', 'BETWEEN', '6000', '20000', NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (127, 9, 1, NULL, 'EQUAL', '100', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (128, 9, 2, NULL, 'LESS', '100', NULL, NULL, 'RED', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (129, 11, 1, NULL, 'EQUAL', ' TO', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (130, 11, 2, NULL, 'EQUAL', ' B.', NULL, NULL, 'GREEN', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (131, 11, 3, NULL, 'EQUAL', ' C.', NULL, NULL, 'YELLOW', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (132, 11, 4, NULL, 'EQUAL', ' D.', NULL, NULL, 'ORANGE', NULL, 4);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (133, 1, 1, ' cycles', ' EQUAL', '0', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (134, 1, 2, ' Returns to the institution after (years)', 'GREATER_OR_EQUAL', '1', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (135, 1, 3, ' canceled cycles', 'GREATER', '0', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (136, 2, 1, ' Complete and canceled cycles main BC products', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (137, 3, 1, ' Amount increase percentages', 'LESS_OR_EQUAL', '60', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (138, 3, 2, ' Amount increase percentages', 'GREATER', '60', NULL, NULL, 'ORANGE', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (139, 4, 1, ' Clients', 'EQUAL', ' All', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (140, 28, 1, ' Clients', 'EQUAL', ' All', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (141, 5, 1, ' new client age', 'BETWEEN', '18', '70', NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (142, 5, 2, ' New client age (Exception)', 'BETWEEN', '71', '75', NULL, 'YELLOW', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (143, 5, 3, ' New customer age (Rejected)', 'NOT_BETWEEN', '18', '75', NULL, 'RED', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (144, 5, 4, ' Recurring customer age', 'BETWEEN', '18', '75', NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (145, 5, 5, ' Recurring customer age (Rejected)', 'NOT_BETWEEN', '18', '75', NULL, 'RED', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (146, 6, 1, ' Recredit (URBAN)', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (147, 6, 2, ' Recredit (RURAL)', 'GREATER_OR_EQUAL', '4', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (148, 7, 1, ' Recredit (URBAN)', 'BETWEEN', '5000', '20000', NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (149, 7, 2, ' Recredit (RURAL)', 'BETWEEN', '5000', '20000', NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (150, 9, 1, NULL, 'EQUAL', '100', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (151, 9, 2, NULL, 'LESS', '100', NULL, NULL, 'RED', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (152, 11, 1, NULL, 'EQUAL', ' TO', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (153, 11, 2, NULL, 'EQUAL', ' B.', NULL, NULL, 'GREEN', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (154, 11, 3, NULL, 'EQUAL', ' C.', NULL, NULL, 'YELLOW', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (155, 11, 4, NULL, 'EQUAL', ' D.', NULL, NULL, 'ORANGE', NULL, 5);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (156, 12, 1, ' current main product', 'EQUAL', '1', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (157, 13, 1, '', 'EQUAL', ' TO', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (158, 13, 2, '', 'EQUAL', ' B.', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (159, 13, 3, '', 'EQUAL', ' C.', '', NULL, 'ORANGE', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (160, 13, 4, '', 'EQUAL', ' D.', '', NULL, 'ORANGE', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (161, 2, 1, ' Completed and canceled cycles on main products', 'GREATER_OR_EQUAL', '3', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (162, 2, 2, ' Completed and canceled cycles on main products', 'EQUAL', '2', '', NULL, 'ORANGE', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (163, 2, 3, ' Completed and canceled cycles on main products', 'LESS', '2', '', NULL, 'RED', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (164, 14, 1, ' Cycle', 'LESS_OR_EQUAL', '4', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (165, 14, 2, ' Cycle', 'EQUAL', '5', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (166, 14, 3, ' Cycle', 'GREATER_OR_EQUAL', '6', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (167, 4, 1, ' Photographs', 'GREATER_OR_EQUAL', '3', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (168, 15, 1, ' without endorsement', 'BETWEEN', '3001', '5000', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (169, 15, 2, ' with an endorsement', 'BETWEEN', '5001', '10000', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (170, 15, 3, ' With two endorsements', 'BETWEEN', '10001', '15000', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (171, 15, 4, ' Acceptance guarantees', 'EQUAL', ' TO', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (172, 15, 5, ' Acceptance guarantees', 'EQUAL', ' B.', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (173, 15, 6, ' Acceptance guarantees', 'EQUAL', ' C.', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (174, 15, 7, ' Rejected guarantees', 'EQUAL', ' D.', '', NULL, 'RED', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (175, 16, 1, ' canceled cycles', 'EQUAL', '4', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (176, 16, 2, ' canceled cycles', 'GREATER', '4', '', NULL, 'ORANGE', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (177, 17, 1, 'Members of the MAIN PRODUCT', 'LESS_OR_EQUAL', '50', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (178, 17, 2, ' How many members have parallel credit', 'LESS_OR_EQUAL', '50', '', NULL, 'GREEN', NULL, 7);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (179, 12, 1, ' Main product (Community Bank or Solidarity Group)', ' GREATER_OR_EQUAL', '1', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (180, 13, 1, '', 'BETWEEN', ' TO', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (181, 13, 2, '', 'BETWEEN', ' B.', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (182, 13, 3, '', 'BETWEEN', ' C.', '', NULL, 'ORANGE', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (183, 13, 4, '', 'BETWEEN', ' D.', '', NULL, 'ORANGE', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (184, 2, 1, ' Completed and canceled cycles on main products', 'GREATER_OR_EQUAL', '1', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (185, 2, 2, ' Completed and canceled cycles on main products', 'EQUAL', '0', '', NULL, 'RED', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (186, 14, 1, ' Client is in cycle 2', 'LESS_OR_EQAL', '2000', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (187, 14, 2, ' Client is in cycle 3', 'LESS_OR_EQUAL', '3000', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (188, 14, 3, ' The loan amount cannot be', 'GREATER', ' main loan', '', NULL, 'RED', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (189, 14, 4, ' The loan amount cannot be', 'GREATER', '3000', '', NULL, 'RED', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (190, 16, 1, ' canceled cycles', 'EQUAL', '4', '', NULL, 'GREEN', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (191, 16, 2, ' canceled cycles', 'GREATER', '4', '', NULL, 'ORANGE', NULL, 3);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (192, 18, 1, ' New', 'EQUAL', ' Women', '', NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (193, 18, 2, ' recredit', 'EQUAL', ' Women', '', NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (194, 18, 3, ' Asset', 'EQUAL', ' Yeah', '', NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (195, 5, 1, ' New', 'BETWEEN', '20', '60', NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (196, 5, 2, ' recredit', 'NOT_BETWEEN', '20', '60', NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (197, 5, 3, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (198, 19, 1, ' New', 'EQUAL', ' Guatemala', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (199, 19, 2, ' New', 'EQUAL', ' foreign', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (200, 19, 3, ' recredit', 'EQUAL', ' Guatemala', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (201, 19, 4, ' recredit', 'EQUAL', ' foreign', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (202, 19, 5, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (203, 20, 1, ' Asset', 'EQUAL', ' No', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (204, 21, 1, ' Asset', 'EQUAL', ' No', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (205, 22, 1, ' New', 'EQUAL', ' No', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (206, 22, 2, ' New', 'EQUAL', ' Yeah', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (207, 22, 3, ' recredit', 'EQUAL', ' No', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (208, 22, 4, ' recredit', 'EQUAL', ' Yeah', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (209, 22, 5, ' Asset', 'EQUAL', ' No', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (210, 23, 1, ' New', 'EQUAL', ' own or family', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (211, 23, 2, ' New', 'EQUAL', ' rented or paying', NULL, NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (212, 23, 3, ' recredit', 'EQUAL', ' own or family', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (213, 23, 4, ' recredit', 'EQUAL', ' own or family', NULL, NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (214, 23, 5, ' recredit', 'EQUAL', ' rented or paying', NULL, NULL, 'ORANGE', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (215, 23, 6, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (216, 24, 1, ' New (years)', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (217, 24, 2, ' New (years)', 'LESS', '3', NULL, NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (218, 24, 3, ' Recredits (years)', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (219, 24, 4, ' Recredits (years)', 'LESS', '3', NULL, NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (220, 24, 5, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (221, 25, 1, ' New (years)', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (222, 25, 2, ' New (years)', 'BETWEEN', '1.5', '3', NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (223, 25, 3, ' New (years)', 'LESS', '1.5', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (224, 25, 4, ' Recredits (years)', 'GREATER_OR_EQUAL', '3', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (225, 25, 5, ' Recredits (years)', 'BETWEEN', '1.5', '3', NULL, 'YELLOW', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (226, 25, 6, ' Recredits (years)', 'LESS', '1.5', NULL, NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (227, 25, 7, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (228, 14, 1, ' New', 'NOT_BETWEEN', '10000', '200000', NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (229, 14, 2, 'recredits', 'NOT_BETWEEN', '10000', '200000', NULL, 'RED', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (230, 14, 5, ' Asset', 'EQUAL', ' Yeah', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (231, 26, 1, ' Have the principal balance of the canceled credit', 'EQUAL', '50', NULL, NULL, 'GREEN', NULL, 6);
INSERT INTO `fineract_default`.`checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `reference`, `condition`, `first_value`, `second_value`, `value_list`, `color`, `description`, `product_id`) VALUES (232, 26, 2, '', ' <>', ' Green', NULL, NULL, 'RED', NULL, 6);
