--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- liquibase formatted sql
-- changeset fineract:1
-- MySQL dump 10.13  Distrib 5.1.60, for Win32 (ia32)
--
-- Host: localhost    Database: fineract_default
-- ------------------------------------------------------
-- Server version	5.1.60-community

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES UTF8MB4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Insert checklist decision making values
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (1, 1, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (2, 1, 2, 1, 'Returns to the institution after (years)', 4, '1', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (3, 1, 3, 1, 'Canceled cycles', 3, '0', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (4, 2, 1, 1, 'Cycles', 3, '0', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (5, 3, 1, 1, 'Amount increase Percentage', 1, '200', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (6, 3, 2, 1, 'Amount increase Percentage', 7, '201', '500', NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (7, 3, 3, 1, 'Amount increase Percentage', 3, '500', NULL, NULL, 4, 'EXCEPTION', 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (8, 4, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (9, 4, 2, 1, 'Returns After Years', 4, '1', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (10, 4, 3, 1, 'Canceled Cycles', 3, '0', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (11, 4, 4, 1, 'Requested Amount', 3, '6000', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (12, 5, 1, 1, 'New Client Age', 7, '18', '70', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (13, 5, 2, 1, 'New Client Age', 7, '71', '75', NULL, 2, 'EXCEPTION', 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (14, 5, 3, 1, 'New Client Age', 8, '18', '75', NULL, 4, 'REJECT', 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (15, 5, 4, 1, 'Recurring Client Age', 7, '18', '75', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (16, 5, 5, 1, 'Recurring Client Age', 8, '18', '75', NULL, 4, 'REJECT', 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (17, 6, 1, 2, 'New (URBAN)', 4, '7', '', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (18, 6, 2, 2, 'Recredit (URBAN)', 4, '7', '', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (19, 6, 3, 2, 'New (RURAL)', 4, '10', '', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (20, 6, 4, 2, 'Recredit (RURAL)', 4, '10', '', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (21, 7, 1, 2, 'New (URBAN)', 7, '1500', '5000', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (22, 7, 2, 2, 'Recredit (URBAN)', 7, '1500', '15000', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (23, 7, 3, 2, 'New (RURAL)', 7, '1500', '5000', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (24, 7, 4, 2, 'Recredit (RURAL)', 7, '1500', '15000', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (25, 8, 1, 2, 'New (URBAN)', 7, '1', '3', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (26, 8, 2, 2, 'New (URBAN)', 3, '3', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (27, 8, 3, 2, 'Recredit (URBAN)', 7, '1', '4', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (28, 8, 4, 2, 'Recredit (URBAN)', 3, '4', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (29, 8, 5, 2, 'New (RURAL)', 7, '1', '3', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (30, 8, 6, 2, 'New (RURAL)', 3, '3', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (31, 8, 7, 2, 'Recredit (RURAL)', 7, '1', '4', NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (32, 8, 8, 2, 'Recredit (RURAL)', 3, '4', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (33, 9, 1, 2, NULL, 6, '20', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (34, 9, 2, 2, NULL, 3, '20', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (35, 10, 1, 2, NULL, 6, '50', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (36, 10, 2, 2, NULL, 3, '50', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (37, 11, 1, 2, '', 1, 'TO', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (38, 11, 2, 2, '', 1, 'B.', NULL, NULL, 1, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (39, 11, 3, 2, '', 1, 'C.', NULL, NULL, 2, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (40, 11, 4, 2, '', 1, 'D.', NULL, NULL, 3, NULL, 2);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (41, 1, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (42, 1, 2, 1, 'Returns to the institution after (years)', 4, '1', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (43, 1, 3, 1, 'Canceled cycles', 3, '0', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (44, 2, 1, 1, 'Cycles', 3, '0', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (45, 3, 1, 1, 'Amount increase Percentage', 1, '200', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (46, 3, 2, 1, 'Amount increase Percentage', 7, '201', '500', NULL, 2, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (47, 3, 3, 1, 'Amount increase Percentage', 3, '500', NULL, NULL, 4, 'EXCEPTION', 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (48, 4, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (49, 4, 2, 1, 'Returns After Years', 4, '1', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (50, 4, 3, 1, 'Canceled Cycles', 3, '0', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (51, 4, 4, 1, 'Requested Amount', 3, '6000', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (52, 5, 1, 1, 'New Client Age', 7, '18', '70', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (53, 5, 2, 1, 'New Client Age', 7, '71', '75', NULL, 2, 'EXCEPTION', 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (54, 5, 3, 1, 'New Client Age', 8, '18', '75', NULL, 4, 'REJECT', 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (55, 5, 4, 1, 'Recurring Client Age', 7, '18', '75', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (56, 5, 5, 1, 'Recurring Client Age', 8, '18', '75', NULL, 4, 'REJECT', 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (57, 27, 1, 2, 'Recredit (URBAN)', 4, '1', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (58, 27, 2, 2, 'Recredit (RURAL)', 4, '1', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (59, 6, 1, 2, 'Recredit (URBAN)', 4, '4', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (60, 6, 2, 2, 'Recredit (URBAN)', 5, '4', NULL, NULL, 3, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (61, 6, 3, 2, 'Recredit (RURAL)', 4, '4', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (62, 6, 4, 2, 'Recredit (RURAL)', 5, '4', NULL, NULL, 3, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (63, 7, 1, 2, 'Recredit (URBAN)', 7, '1500', '15000', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (64, 7, 2, 2, 'Recredit (RURAL)', 7, '1500', '15000', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (65, 8, 1, 2, 'Recredit (URBAN)', 7, '1', '3', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (66, 8, 2, 2, 'Recredit (URBAN)', 3, '3', NULL, NULL, 2, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (67, 8, 3, 2, 'Recredit (RURAL)', 7, '1', '3', NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (68, 8, 4, 2, 'Recredit (RURAL)', 3, '3', NULL, NULL, 2, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (69, 11, 1, 2, '', 1, 'TO', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (70, 11, 2, 2, '', 1, 'B.', NULL, NULL, 1, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (71, 11, 3, 2, '', 1, 'C.', NULL, NULL, 2, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (72, 11, 4, 2, '', 1, 'D.', NULL, NULL, 3, NULL, 9);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (73, 1, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (74, 1, 2, 1, 'Returns to the institution after (years)', 4, '1', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (75, 1, 3, 1, 'Canceled cycles', 3, '0', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (76, 2, 1, 1, 'Cycles', 3, '0', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (77, 3, 1, 1, 'Amount increase Percentage', 1, '200', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (78, 3, 2, 1, 'Amount increase Percentage', 7, '201', '500', NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (79, 3, 3, 1, 'Amount increase Percentage', 3, '500', NULL, NULL, 4, 'EXCEPTION', 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (80, 4, 1, 1, 'Clients', 1, 'ALL', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (81, 28, 1, 1, 'Clients', 1, 'ALL', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (82, 5, 1, 1, 'New Client Age', 7, '18', '70', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (83, 5, 2, 1, 'New Client Age', 7, '71', '75', NULL, 2, 'EXCEPTION', 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (84, 5, 3, 1, 'New Client Age', 8, '18', '75', NULL, 4, 'REJECT', 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (85, 5, 4, 1, 'Recurring Client Age', 7, '18', '75', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (86, 5, 5, 1, 'Recurring Client Age', 8, '18', '75', NULL, 4, 'REJECT', 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (87, 6, 1, 2, 'New (URBAN)', 4, '7', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (88, 6, 2, 2, 'New (URBAN)', 5, '7', NULL, NULL, 3, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (89, 6, 3, 2, 'Recredit (URBAN)', 4, '7', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (90, 6, 4, 2, 'Recredit (URBAN)', 5, '7', NULL, NULL, 3, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (91, 6, 5, 2, 'New (RURAL)', 4, '10', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (92, 6, 6, 2, 'New (RURAL)', 5, '10', NULL, NULL, 3, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (93, 6, 7, 2, 'Recredit (RURAL)', 4, '10', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (94, 6, 8, 2, 'Recredit (RURAL)', 5, '10', NULL, NULL, 3, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (95, 7, 1, 2, 'New (URBAN)', 7, '1000', '4999', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (96, 7, 2, 2, 'Recredit (URBAN)', 7, '1000', '20000', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (97, 7, 3, 2, 'New (RURAL)', 7, '1000', '4999', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (98, 7, 4, 2, 'Recredit (RURAL)', 7, '1000', '20000', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (99, 8, 1, 2, 'New (URBAN)', 7, '1', '3', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (100, 8, 2, 2, 'New (URBAN)', 3, '3', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (101, 8, 3, 2, 'Recredit (URBAN)', 7, '1', '3', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (102, 8, 4, 2, 'Recredit (URBAN)', 3, '3', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (103, 8, 5, 2, 'New (RURAL)', 7, '1', '3', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (104, 8, 6, 2, 'New (RURAL)', 3, '3', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (105, 8, 7, 2, 'Recredit (RURAL)', 7, '1', '3', NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (106, 8, 8, 2, 'Recredit (RURAL)', 3, '3', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (107, 10, 1, 2, NULL, 4, '50', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (108, 10, 2, 2, NULL, 3, '50', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (109, 11, 1, 2, NULL, 1, 'TO', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (110, 11, 2, 2, NULL, 1, 'B.', NULL, NULL, 1, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (111, 11, 3, 2, NULL, 1, 'C.', NULL, NULL, 2, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (112, 11, 4, 2, NULL, 1, 'D.', NULL, NULL, 3, NULL, 8);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (113, 1, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (114, 1, 2, 1, 'Returns to the institution after (years)', 4, '1', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (115, 1, 3, 1, 'Canceled cycles', 3, '0', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (116, 2, 1, 1, 'Complete and canceled cycles main BC products', 4, '3', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (117, 3, 1, 1, 'Amount increase percentages', 6, '60', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (118, 3, 2, 1, 'Amount increase percentages', 5, '60', NULL, NULL, 3, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (119, 4, 1, 1, 'Clients', 1, 'ALL', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (120, 5, 1, 1, 'new client age', 7, '18', '70', NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (121, 5, 2, 1, 'New client age (Exception)', 7, '71', '75', NULL, 2, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (122, 5, 3, 1, 'New customer age (Rejected)', 8, '18', '75', NULL, 4, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (123, 5, 4, 1, 'Recurring customer age', 7, '18', '75', NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (124, 5, 5, 1, 'Recurring customer age (Rejected)', 8, '18', '75', NULL, 4, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (125, 6, 1, 2, 'Recredit (URBAN)', 4, '3', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (126, 6, 2, 2, 'Recredit (RURAL)', 4, '4', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (127, 29, 1, 2, 'Recrédito (URBANO), 1 new client for how many recurring clients', 1, '3', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (128, 29, 2, 2, 'Recredito (RURAL), 1 new client for how many recurring clients', 1, '3', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (129, 7, 1, 2, 'Recredit (URBAN)', 7, '6000', '20000', NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (130, 7, 2, 2, 'Recredit (RURAL)', 7, '6000', '20000', NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (131, 9, 1, 2, NULL, 1, '100', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (132, 9, 2, 2, NULL, 5, '100', NULL, NULL, 4, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (133, 11, 1, 2, NULL, 1, 'TO', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (134, 11, 2, 2, NULL, 1, 'B.', NULL, NULL, 1, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (135, 11, 3, 2, NULL, 1, 'C.', NULL, NULL, 2, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (136, 11, 4, 2, NULL, 1, 'D.', NULL, NULL, 3, NULL, 4);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (137, 1, 1, 1, 'Cycles', 1, '0', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (138, 1, 2, 1, 'Returns to the institution after (years)', 4, '1', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (139, 1, 3, 1, 'Canceled cycles', 3, '0', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (140, 2, 1, 1, 'Complete and canceled cycles main BC products', 4, '3', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (141, 3, 1, 1, 'Amount increase percentages', 6, '60', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (142, 3, 2, 1, 'Amount increase percentages', 3, '60', NULL, NULL, 3, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (143, 4, 1, 1, 'Clients', 1, ' All', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (144, 28, 1, 1, 'Clients', 1, ' All', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (145, 5, 1, 1, 'New client age', 7, '18', '70', NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (146, 5, 2, 1, 'New client age (Exception)', 7, '71', '75', NULL, 2, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (147, 5, 3, 1, 'New customer age (Rejected)', 8, '18', '75', NULL, 4, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (148, 5, 4, 1, 'Recurring customer age', 7, '18', '75', NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (149, 5, 5, 1, 'Recurring customer age (Rejected)', 8, '18', '75', NULL, 4, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (150, 6, 1, 2, 'Recredit (URBAN)', 4, '3', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (151, 6, 2, 2, 'Recredit (RURAL)', 4, '4', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (152, 7, 1, 2, 'Recredit (URBAN)', 7, '5000', '20000', NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (153, 7, 2, 2, 'Recredit (RURAL)', 7, '5000', '20000', NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (154, 9, 1, 2, NULL, 1, '100', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (155, 9, 2, 2, NULL, 5, '100', NULL, NULL, 4, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (156, 11, 1, 2, NULL, 1, 'TO', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (157, 11, 2, 2, NULL, 1, 'B.', NULL, NULL, 1, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (158, 11, 3, 2, NULL, 1, 'C.', NULL, NULL, 2, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (159, 11, 4, 2, NULL, 1, 'D.', NULL, NULL, 3, NULL, 5);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (160, 12, 1, 1, 'Current main product', 1, '1', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (161, 13, 1, 1, '', 1, 'TO', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (162, 13, 2, 1, '', 1, 'B.', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (163, 13, 3, 1, '', 1, 'C.', '', NULL, 3, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (164, 13, 4, 1, '', 1, 'D.', '', NULL, 3, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (165, 2, 1, 1, 'Completed and canceled cycles on main products', 4, '3', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (166, 2, 2, 1, 'Completed and canceled cycles on main products', 1, '2', '', NULL, 3, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (167, 2, 3, 1, 'Completed and canceled cycles on main products', 5, '2', '', NULL, 4, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (168, 14, 1, 1, 'Cycle', 6, '4', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (169, 14, 2, 1, 'Cycle', 1, '5', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (170, 14, 3, 1, 'Cycle', 4, '6', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (171, 4, 1, 1, 'Photographs', 4, '3', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (172, 15, 1, 1, 'Without endorsement', 7, '3001', '5000', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (173, 15, 2, 1, 'With an endorsement', 7, '5001', '10000', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (174, 15, 3, 1, 'With two endorsements', 7, '10001', '15000', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (175, 15, 4, 1, 'Acceptance guarantees', 1, 'TO', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (176, 15, 5, 1, 'Acceptance guarantees', 1, 'B.', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (177, 15, 6, 1, 'Acceptance guarantees', 1, 'C.', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (178, 15, 7, 1, 'Rejected guarantees', 1, 'D.', '', NULL, 4, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (179, 16, 1, 1, 'Canceled cycles', 1, '4', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (180, 16, 2, 1, 'Canceled cycles', 3, '4', '', NULL, 3, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (181, 17, 1, 1, 'Members of the MAIN PRODUCT', 6, '50', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (182, 17, 2, 1, 'How many members have parallel credit', 6, '50', '', NULL, 1, NULL, 7);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (183, 12, 1, 1, 'Main product (Community Bank or Solidarity Group)', 4, '1', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (184, 13, 1, 1, '', 7, 'TO', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (185, 13, 2, 1, '', 7, 'B.', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (186, 13, 3, 1, '', 7, 'C.', '', NULL, 3, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (187, 13, 4, 1, '', 7, 'D.', '', NULL, 3, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (188, 2, 1, 1, 'Completed and canceled cycles on main products', 4, '1', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (189, 2, 2, 1, 'Completed and canceled cycles on main products', 1, '0', '', NULL, 4, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (190, 14, 1, 1, 'Client is in cycle 2', 'LESS_OR_EQAL', '2000', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (191, 14, 2, 1, 'Client is in cycle 3', 6, '3000', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (192, 14, 3, 1, 'The loan amount cannot be', 3, ' main loan', '', NULL, 4, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (193, 14, 4, 1, 'The loan amount cannot be', 3, '3000', '', NULL, 4, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (194, 16, 1, 1, 'Canceled cycles', 1, '4', '', NULL, 1, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (195, 16, 2, 1, 'Canceled cycles', 3, '4', '', NULL, 3, NULL, 3);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (196, 18, 1, 1, 'New', 1, ' Women', '', NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (197, 18, 2, 1, 'Recredit', 1, ' Women', '', NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (198, 18, 3, 1, 'Asset', 1, 'YES', '', NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (199, 5, 1, 1, 'New', 7, '20', '60', NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (200, 5, 2, 1, 'Recredit', 8, '20', '60', NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (201, 5, 3, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (202, 19, 1, 1, 'New', 1, ' Guatemala', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (203, 19, 2, 1, 'New', 1, ' foreign', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (205, 19, 4, 1, 'Recredit', 1, ' foreign', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (206, 19, 5, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (207, 20, 1, 1, 'Asset', 1, 'NO', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (208, 21, 1, 1, 'Asset', 1, 'NO', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (209, 22, 1, 1, 'New', 1, 'NO', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (210, 22, 2, 1, 'New', 1, 'YES', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (211, 22, 3, 1, 'Recredit', 1, 'NO', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (212, 22, 4, 1, 'Recredit', 1, 'YES', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (213, 22, 5, 1, 'Asset', 1, 'NO', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (214, 23, 1, 1, 'New', 1, ' own or family', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (215, 23, 2, 1, 'New', 1, ' rented or paying', NULL, NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (216, 23, 3, 1, 'Recredit', 1, ' own or family', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (217, 23, 4, 1, 'Recredit', 1, ' own or family', NULL, NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (218, 23, 5, 1, 'Recredit', 1, ' rented or paying', NULL, NULL, 3, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (219, 23, 6, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (220, 24, 1, 1, 'New (years)', 4, '3', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (221, 24, 2, 1, 'New (years)', 5, '3', NULL, NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (222, 24, 3, 1, 'Recredits (years)', 4, '3', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (223, 24, 4, 1, 'Recredits (years)', 5, '3', NULL, NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (224, 24, 5, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (225, 25, 1, 1, 'New (years)', 4, '3', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (226, 25, 2, 1, 'New (years)', 7, '1.5', '3', NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (227, 25, 3, 1, 'New (years)', 5, '1.5', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (228, 25, 4, 1, 'Recredits (years)', 4, '3', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (229, 25, 5, 1, 'Recredits (years)', 7, '1.5', '3', NULL, 2, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (230, 25, 6, 1, 'Recredits (years)', 5, '1.5', NULL, NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (231, 25, 7, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (232, 14, 1, 1, 'New', 8, '10000', '200000', NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (233, 14, 2, 1, 'Recredits', 8, '10000', '200000', NULL, 4, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (234, 14, 5, 1, 'Asset', 1, 'YES', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (235, 26, 1, 1, 'Have the principal balance of the canceled credit', 1, '50', NULL, NULL, 1, NULL, 6);
INSERT INTO `checklist_decision_making` (`id`, `checklist_category_id`, `sequence`, `validation_type_enum`, `reference`, `conditional_operator`, `first_value`, `second_value`, `value_list`, `color_enum`, `description`, `product_id`) VALUES (236, 26, 2, 1, '', 2, '50', NULL, NULL, 4, NULL, 6);
