--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements. See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership. The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License. You may obtain a copy of the License at
--
-- http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

-- liquibase formatted sql
-- changeset fineract:1
-- MySQL dump 10.13  Distrib 5.1.60, for Win32 (ia32)
--
-- Host: localhost    Database: fineract_default
-- ------------------------------------------------------
-- Server version	5.1.60-community

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES UTF8MB4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (4, 545, 'DPI de propietario de la garantía (a nombre de terceros)', 'DPI de propietario de la garantía (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 14:38:49', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (5, 545, 'Constancia de residencia del propietario de la garantía (a nombre de terceros)', 'Constancia de residencia del propietario de la garantía (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 14:39:14', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (6, 545, 'Visto bueno de Coordinadora Legal (si es la misma garantía agregar correo de VoBo)', 'Visto bueno de Coordinadora Legal (si es la misma garantía agregar correo de VoBo)', 'PDF', 4, '2026-01-22 14:51:58', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (7, 545, 'Original del Primer Testimonio o Derecho de Posesión', 'Original del Primer Testimonio o Derecho de Posesión', 'PDF', 4, '2026-01-22 14:59:33', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (8, 545, 'Fotografias de la garantia y debe figurar la solicitante, con coordenadas)', 'Fotografias de la garantia y debe figurar la solicitante, con coordenadas)', 'IMAGE', 4, '2026-01-22 14:59:54', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (9, 545, 'Avalúo por empresa valuadora', 'Avalúo por empresa valuadora', 'PDF', 4, '2026-01-22 15:00:20', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (10, 545, 'Carta de consentimiento (a nombre de terceros)', 'Carta de consentimiento (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 15:00:53', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (18, 542, 'Fotocopia completa de DPI', 'Fotocopia completa de DPI', 'PDF', 4, '2026-01-22 15:18:50', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (19, 542, 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'PDF', 4, '2026-01-22 15:19:01', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (20, 542, 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'PDF/IMAGE', 4, '2026-01-22 15:19:19', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (21, 542, 'Formulario de visita al negocio y vivienda:', 'Formulario de visita al negocio y vivienda:', 'EXCEL', 4, '2026-01-22 15:19:33', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (22, 542, 'Formularios de información del fiador empresario', 'Formularios de información del fiador empresario', 'PDF', 4, '2026-01-22 15:19:46', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (23, 542, 'Fotografias del Negocio del fiador, debe figurar fiador y asesor (minimo 3 fotografías con coordenadas).', 'Fotografias del Negocio del fiador, debe figurar fiador y asesor (minimo 3 fotografías con coordenadas).', 'IMAGE', 4, '2026-01-22 15:19:59', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (24, 542, 'Fotografias de la vivienda (con coordenadas)', 'Fotografias de la vivienda (con coordenadas)', 'IMAGE', 4, '2026-01-22 15:20:14', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (25, 542, 'Por lo menos uno de los siguientes documentos (patente de comercio, RTU, Tarjeta de salud, contrato de clientes, facturas de compras)', 'Por lo menos uno de los siguientes documentos (patente de comercio, RTU, Tarjeta de salud, contrato de clientes, facturas de compras)', 'PDF/IMAGE', 4, '2026-01-22 15:20:32', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (26, 543, 'Fotocopia completa de DPI', 'Fotocopia completa de DPI', 'PDF', 4, '2026-01-22 15:22:13', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (27, 543, 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'PDF', 4, '2026-01-22 15:22:23', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (28, 543, 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'PDF/IMAGE', 4, '2026-01-22 15:22:33', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (29, 543, 'Constancia de participación en capacitaciones o ENF', 'Constancia de participación en capacitaciones o ENF', 'PDF', 4, '2026-01-22 15:22:48', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (30, 546, 'DPI de propietario de la garantía (a nombre de terceros)', 'DPI de propietario de la garantía (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 15:23:27', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (31, 546, 'Constancia de residencia del propietario de la garantía (a nombre de terceros)', 'Constancia de residencia del propietario de la garantía (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 15:23:35', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (32, 546, 'Visto bueno de Coordinadora Legal (si es la misma garantía agregar correo de VoBo)', 'Visto bueno de Coordinadora Legal (si es la misma garantía agregar correo de VoBo)', 'PDF', 4, '2026-01-22 15:23:42', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (33, 546, 'Primer testimonio inscrito en el Registro Nacional de la propiedad', 'Primer testimonio inscrito en el Registro Nacional de la propiedad', 'PDF', 4, '2026-01-22 15:23:51', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (34, 546, 'Certificación del Registro de la Propiedad (sin gravámenes)', 'Certificación del Registro de la Propiedad (sin gravámenes)', 'PDF', 4, '2026-01-22 15:24:02', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (36, 546, 'Fotografias de la garantia y debe figurar la solicitante, con coordenadas)', 'Fotografias de la garantia y debe figurar la solicitante, con coordenadas)', 'IMAGE', 4, '2026-01-22 15:24:58', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (37, 546, 'Avalúo por empresa valuadora', 'Avalúo por empresa valuadora', 'PDF', 4, '2026-01-22 15:25:13', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (38, 546, 'Carta de consentimiento (a nombre de terceros)', 'Carta de consentimiento (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 15:25:23', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (39, 544, 'DPI de propietario de la garantía', 'DPI de propietario de la garantía', 'PDF/IMAGE', 4, '2026-01-22 15:25:46', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (40, 544, 'Constancia de residencia del propietario de la garantía', 'Constancia de residencia del propietario de la garantía', 'PDF/IMAGE', 4, '2026-01-22 15:25:58', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (41, 544, 'Facturas de maquinarias o declaración jurada', 'Facturas de maquinarias o declaración jurada', 'PDF/IMAGE', 4, '2026-01-22 15:26:10', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (42, 544, 'Fotografias de la garantia debe figurar la solicitante, con coordenadas)', 'Fotografias de la garantia debe figurar la solicitante, con coordenadas)', 'IMAGE', 4, '2026-01-22 15:26:28', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (43, 544, 'Avalúo por empresa valuadora', 'Avalúo por empresa valuadora', 'PDF', 4, '2026-01-22 15:26:39', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (44, 544, 'Carta de consentimiento (a nombre de terceros)', 'Carta de consentimiento (a nombre de terceros)', 'PDF/IMAGE', 4, '2026-01-22 15:26:48', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (45, 540, 'Formularios de solicitud de crédito digitales', 'Formularios de solicitud de crédito digitales', 'EXCEL', 4, '2026-01-22 15:27:31', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (46, 540, 'Fotocopia completa de DPI de la deudora', 'Fotocopia completa de DPI de la deudora', 'PDF/IMAGE', 4, '2026-01-22 15:27:42', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (47, 540, 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'PDF/IMAGE', 4, '2026-01-22 15:27:50', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (48, 540, 'Fotografias del Negocio de Crédito Individual, debe figurar clienta y asesor (minimo 3 fotografías con coordenadas).', 'Fotografias del Negocio de Crédito Individual, debe figurar clienta y asesor (minimo 3 fotografías con coordenadas).', 'IMAGE', 4, '2026-01-22 15:28:03', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (49, 540, 'Fotografias de la vivienda(con coordenadas)', 'Fotografias de la vivienda(con coordenadas)', 'IMAGE', 4, '2026-01-22 15:28:15', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (50, 540, 'Informe técnico agrícola (Cuando aplique)', 'Informe técnico agrícola (Cuando aplique)', 'PDF', 4, '2026-01-22 15:28:24', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (51, 540, 'Foto de libreta de ahorros (sólo en caso de transferencia)', 'Foto de libreta de ahorros (sólo en caso de transferencia)', 'PDF/IMAGE', 4, '2026-01-22 15:28:33', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (52, 540, 'Informe de desarrollo empresarial, detalle de ventas y plan de acción.', 'Informe de desarrollo empresarial, detalle de ventas y plan de acción.', 'PDF', 4, '2026-01-22 15:28:46', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (53, 540, 'Formato de monto a retener', 'Formato de monto a retener', 'PDF', 4, '2026-01-22 15:28:58', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (54, 617, 'Formularios de solicitud de crédito digitales', 'Formularios de solicitud de crédito digitales', 'EXCEL', 4, '2026-01-22 16:05:50', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (55, 617, 'Fotocopia completa de DPI de la deudora', 'Fotocopia completa de DPI de la deudora', 'PDF/IMAGE', 4, '2026-01-22 16:05:59', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (56, 617, 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'Recibo de servicios públicos máximo dos meses atrasados donde esté la dirección exacta', 'PDF/IMAGE', 4, '2026-01-22 16:06:09', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (57, 617, 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'En caso no tenga servicios, constancia de risidencia emitida por el COCODE', 'PDF/IMAGE', 4, '2026-01-22 16:06:18', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (58, 617, 'Fotocopia de tarjeta de salud (donde lo requiera las normas guatemaltecas)', 'Fotocopia de tarjeta de salud (donde lo requiera las normas guatemaltecas)', 'PDF/IMAGE', 4, '2026-01-22 16:06:25', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (59, 617, 'Carta de compromiso a participar en el programa firmado por clienta y facilitador.', 'Carta de compromiso a participar en el programa firmado por clienta y facilitador.', 'PDF/IMAGE', 4, '2026-01-22 16:06:36', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (60, 617, 'Segmentación', 'Segmentación', 'PDF/IMAGE', 4, '2026-01-22 16:06:45', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (61, 617, 'Fotocopia de facturas de compra/ venta de mercadería o materia prima', 'Fotocopia de facturas de compra/ venta de mercadería o materia prima', 'PDF/IMAGE', 4, '2026-01-22 16:06:52', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (62, 617, 'Copia del RTU', 'Copia del RTU', 'PDF/IMAGE', 4, '2026-01-22 16:07:02', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (63, 617, 'Fotocopia Patente de Comercio', 'Fotocopia Patente de Comercio', 'PDF/IMAGE', 4, '2026-01-22 16:07:11', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (64, 617, 'Fotocopia Patente de Sociedad', 'Fotocopia Patente de Sociedad', 'PDF/IMAGE', 4, '2026-01-22 16:07:21', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (65, 617, 'Fotografias del Negocio de Crédito Individual, debe figurar clienta y asesor (minimo 3 fotografías con coordenadas).', 'Fotografias del Negocio de Crédito Individual, debe figurar clienta y asesor (minimo 3 fotografías con coordenadas).', 'IMAGE', 4, '2026-01-22 16:07:36', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (66, 617, 'Fotografias de la vivienda(con coordenadas)', 'Fotografias de la vivienda(con coordenadas)', 'IMAGE', 4, '2026-01-22 16:07:52', b'1');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (67, 617, 'Foto de libreta de ahorros (sólo en caso de transferencia)', 'Foto de libreta de ahorros (sólo en caso de transferencia)', 'PDF/IMAGE', 4, '2026-01-22 16:07:59', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (68, 617, 'Informe técnico agrícola (Cuando aplique)', 'Informe técnico agrícola (Cuando aplique)', 'PDF', 4, '2026-01-22 16:08:06', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (69, 617, 'Contrato de arrendamiento (crédito agrícola)', 'Contrato de arrendamiento (crédito agrícola)', 'PDF', 4, '2026-01-22 16:08:13', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (70, 617, 'Informe de desarrollo empresarial, detalle de ventas y plan de acción.', 'Informe de desarrollo empresarial, detalle de ventas y plan de acción.', 'PDF', 4, '2026-01-22 16:08:22', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (71, 617, 'Formato de monto a retener', 'Formato de monto a retener', 'PDF', 4, '2026-01-22 16:08:33', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (72, 617, 'En caso de consolidación de deuda, adjunar documentos como comprobantes de la deuda.', 'En caso de consolidación de deuda, adjunar documentos como comprobantes de la deuda.', 'PDF', 4, '2026-01-22 16:08:40', b'0');
INSERT INTO pae_required_documents (`id`, `category_id`, `document_name`, `description`, `accepted_format`, `created_by`, `created_on`, `required`) VALUES (73, 617, 'Otros', 'Otros', 'PDF/IMAGE', 4, '2026-01-22 16:08:55', b'0');
