---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fineract
  namespace: fineract-dev
  labels:
    app.kubernetes.io/name: fineract
    app.kubernetes.io/instance: fineract
    app_name: fineract
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fineract
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70