---
# Source: fiter-app/charts/fineract/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract
  namespace: fineract-dev
  labels:
    app.kubernetes.io/name: fineract
    app.kubernetes.io/instance: fineract
    app_name: fineract
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fineract
      app.kubernetes.io/instance: fineract
      app_name: fineract
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fineract
        app.kubernetes.io/instance: fineract
        app_name: fineract
    spec:
      serviceAccountName: fineract
      volumes:
      containers:
        - name: fineract
          image: "seyio/fineract:v1.9.0"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          env:
            - name: "FINERACT_DEFAULT_TENANTDB_HOSTNAME"
              value: "SERLINCOREBDDEV.gco.com.co"
            - name: "FINERACT_DEFAULT_TENANTDB_PORT"
              value: "5432"
            - name: "FINERACT_HIKARI_JDBC_URL"
              value: "jdbc:postgresql://SERLINCOREBDDEV.gco.com.co:5432/fineract_tenants"
            - name: "FINERACT_SERVER_PORT"
              value: "8443"
            - name: "FINERACT_SERVER_SSL_ENABLED"
              value: "true"
            - name: "TZ"
              value: "America/Bogota"
            - name: "fineract.allowJobs"
              value: "true"
            - name: "FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME"
              value: "org.postgresql.Driver"
            - name: "fineract_tenants_driver"
              value: "org.postgresql.Driver"
            - name: "fineract_tenants_url"
              value: "jdbc:postgresql://SERLINCOREBDDEV.gco.com.co:5432/fineract_tenants"
            - name: "FINERACT_DEFAULT_TENANTDB_PWD"
              valueFrom:
                secretKeyRef:
                  key: "FINERACT_DEFAULT_TENANTDB_PWD"
                  name: "fineract-secret"
            - name: "FINERACT_DEFAULT_TENANTDB_UID"
              valueFrom:
                secretKeyRef:
                  key: "FINERACT_DEFAULT_TENANTDB_UID"
                  name: "fineract-secret"
            - name: "fineract_tenants_pwd"
              valueFrom:
                secretKeyRef:
                  key: "fineract_tenants_pwd"
                  name: "fineract-secret"
            - name: "fineract_tenants_uid"
              valueFrom:
                secretKeyRef:
                  key: "fineract_tenants_uid"
                  name: "fineract-secret"        
          ports:
            - name: job-port
              containerPort: 8443
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9464
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /fineract-provider/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 5
            httpGet:
              path: /fineract-provider/actuator/health
              port: 8080
            periodSeconds: 300      
          resources:
            limits:
              cpu: 512m
              memory: 1536Mi
            requests:
              cpu: 500m
              memory: 700Mi
