---
# Source: fiter-app/charts/fineract/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineract
  namespace: fineract-dev
  labels:
    app.kubernetes.io/name: fineract
    app.kubernetes.io/instance: fineract
    app_name: fineract