name: Entreamigos fiter CI/CD
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_DB: fineract_tenants
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: git fetch --all
      - name: Set up JDK 17
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'
      - name: Run SpotlessCheck, Build jars and run Sonar Scan
        env:
          ENTRE_AMIGOS_SONAR_HOST_URL: ${{ secrets.ENTRE_AMIGOS_SONAR_HOST_URL }}
          ENTRE_AMIGOS_SONAR_TOKEN: ${{ secrets.ENTRE_AMIGOS_SONAR_TOKEN }}
          ENTRE_AMIGOS_SONAR_PROJECT_KEY: ${{ secrets.ENTRE_AMIGOS_SONAR_PROJECT_KEY }}
          ENTRE_AMIGOS_SONAR_ORGANIZATION_KEY: ${{ secrets.ENTRE_AMIGOS_SONAR_ORGANIZATION_KEY }}
        run: |
          git diff origin/fiter/entreamigos/dev
          gradle wrapper
          ./gradlew wrapper --gradle-version=8.5
          ./gradlew wrapper --version
          # ./gradlew spotlessCheck
          ./gradlew build -x spotlessGroovyGradle -x checkstyleMain -x spotbugsMain -x compileTestJava -x test -x cucumber -x checkstyleTest -x asciidoctorPdf -x asciidoctor -x buildAsciidoc -x spotbugsTest
          # ./gradlew sonar \
          # -Dsonar.host.url=$ENTRE_AMIGOS_SONAR_HOST_URL \
          # -Dsonar.token=$ENTRE_AMIGOS_SONAR_TOKEN \
          # -Dsonar.projectKey=$ENTRE_AMIGOS_SONAR_PROJECT_KEY \
          # -Dsonar.organization=$ENTRE_AMIGOS_SONAR_ORGANIZATION_KEY \
          # -Dsonar.qualitygate.wait=true \
          # --info

      - name: Prepare Test Server
        env:
          FINERACT_DEFAULT_TENANTDB_UID: postgres
          FINERACT_DEFAULT_TENANTDB_PWD: postgres
          FINERACT_HIKARI_JDBC_URL: jdbc:postgresql://localhost:5432/fineract_tenants
          FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: org.postgresql.Driver
          FINERACT_LOGGING_LEVEL: WARN
          FINERACT_DEFAULT_TENANTDB_PORT: 5432
          FINERACT_DEFAULT_TENANTDB_HOSTNAME: localhost
          FINERACT_HIKARI_USERNAME: postgres
          FINERACT_HIKARI_PASSWORD: postgres
          FINERACT_SERVER_PORT: 8443
          FINERACT_DEFAULT_TENANTDB_NAME: fineract_default
          PGPASSWORD: postgres
          RUN_ATF_PROCESS: true

        run: |
          ./gradlew dropPGDB -PdbName=$FINERACT_DEFAULT_TENANTDB_NAME -PdbUserName=$FINERACT_HIKARI_USERNAME -PdbUserPassword=$FINERACT_HIKARI_PASSWORD -PjdbcURL=$FINERACT_HIKARI_JDBC_URL
          ./gradlew createPGDB -PdbName=$FINERACT_DEFAULT_TENANTDB_NAME -PdbUserName=$FINERACT_HIKARI_USERNAME -PdbUserPassword=$FINERACT_HIKARI_PASSWORD -PjdbcURL=$FINERACT_HIKARI_JDBC_URL
          ./fineract-qa/pipetools/restore_dev_db.sh

          ./gradlew --no-daemon --console=plain :fineract-provider:bootRun -q -x rat -x compileTestJava -x test --info & curl --connect-timeout 5 --retry 120 --retry-delay 5 --retry-connrefused -k https://localhost:8443/fineract-provider/actuator/health

      - name: Run ATF QA Collections
        run: |
          if([ "$RUN_ATF_PROCESS" != "true" ]); then
            echo "Skipping ATF QA Collections as RUN_ATF_PROCESS is not set to true"
            # exit 0
          fi

          npm install -g newman newman-reporter-html
          npm install -g newman-reporter-htmlextra

          timestamp=$(date +'%Y%m%d-%H%M%S')
          export NEWMAN_REPORT_PATH="fineract-qa/results/report-$timestamp.txt"

          mkdir fineract-qa/results
          rm -rf fineract-qa/results/*
          set +e
          TEST_FAIL=false

          echo "###############################################################################################"
          echo "#"
          echo "# ⏳ Will run the collections now... Hold your breath and fingers crossed!"
          echo "#"
          for collection in fineract-qa/collections/*.postman_collection.json; do
            collection_name=$(basename "$collection" .postman_collection.json)
            export COLLECTION_REPORT_PATH="fineract-qa/results/${collection_name}.txt"
            export COLLECTION_REPORT_PATH_JSON="fineract-qa/results/${collection_name}.json"

            printf "#    🔹 $collection_name -> "

            newman run "$collection" \
              -e "fineract-qa/environments/EA-Localhost.postman_environment.json" \
              -k \
              --verbose \
              --reporter-cli-show-body \
              --reporter-json-export "$COLLECTION_REPORT_PATH_JSON" \
              --reporter-htmlextra-export "$COLLECTION_REPORT_PATH" >> "$COLLECTION_REPORT_PATH"

            RESULT=$?
            if [ $RESULT -ne 0 ]; then
              printf "❌ failed\r"
              TEST_FAIL=true
            else
              printf "✅ OK\r"
            fi

          done
          echo "#"
          echo "# ✨ End of Executing collections"

          if [ "$TEST_FAIL" = "true" ]; then
            echo "#"
            echo "# ⚠️ One collection (or more) failed."
          fi

          echo "#"
          echo "###############################################################################################"

          if [ "$TEST_FAIL" = "true" ]; then
            exit 1
          fi

      - name: Upload QA Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: atf-reports-${{ github.run_id }}
          path: fineract-qa/results/*.*

      - name: ATF QA collections error checker
        if: failure()
        run: |
          echo "⚠️ One collection (or more) failed. Check all details at Upload QA Reports."
          exit 1

      - name: Run Integration Tests
        run: |
          ./gradlew --no-daemon --console=plain :integration-tests:cleanTest :integration-tests:test -PcargoDisabled --info

      - name: Stop Test Server
        run: |
          ./gradlew --stop

  continuous-integration:
    if: github.ref == 'refs/heads/fiter/entreamigos/dev'
    needs: [integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Git
        run: git fetch --unshallow || true

      - uses: kamiazya/setup-graphviz@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LATAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LATAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Replace client specific configs
        run: |
          chmod +x .github/scripts/replace-client-specific-configs.sh
          ./.github/scripts/replace-client-specific-configs.sh

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: latam-backend
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:entreamigos_$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:entreamigos_$IMAGE_TAG

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:entreamigos_latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:entreamigos_latest
