name: Sumas ecr image builder
on:
  push:
    branches:
      - fiter/sumas/dev
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Git
        run: git fetch --unshallow || true

      - uses: kamiazya/setup-graphviz@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LATAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LATAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Replace client specific configs
        run: |
          chmod +x .github/scripts/replace-client-specific-configs.sh
          ./.github/scripts/replace-client-specific-configs.sh 

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: latam-backend
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:sumas_$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:sumas_$IMAGE_TAG

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:sumas_latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:sumas_latest
