name: Albo Fineract Dev CI
on:
  push:
    branches:
      - fiter/albo/dev
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: kamiazya/setup-graphviz@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LATAM_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LATAM_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: latam-backend
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      #Checkout remote repository
      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: fiterlatam/gitops-argocd
          token: ${{ secrets.PAT }}
          ref: fiter/albo/dev

      - name: Update YAML file
        run: |
          sed -i 's/dev-backend.*/dev-backend:${{ steps.commit.outputs.short }}/' helm/back-deployment.yaml

      - name: Commit changes
        run: |
          git config --global user.email "git.latam@fiter.io"
          git config --global user.name "fiterlatam"
          git add .
          git commit -am "Fineract - update Docker image tag to ${{ steps.commit.outputs.short }}"
          git push
          
